[[linux]]
  name = "Distributions"
  url = "/linux/distributions/"
  weight = 1

[[linux]]
  name = "Debian"
  url = "/linux/debian/"
  weight = 2

[[linux]]
  name = "Random"
  url = "/linux/random/"
  weight = 3

[[dart]]
  name = "Dart"
  url = "/dart/dart/"
  weight = 1

[[dart]]
  name = "Design Patterns"
  url = "/dart/design_patterns/"
  weight = 2

[[main]]
  name = "Linux"
  url = "/linux/distributions/distributions/"
  weight = 3

[[main]]
  name = "Python"
  url = "/python/tutorial/chapter_1/"
  weight = 1

[[main]]
  name = "Dart"
  url = "/dart/dart/comments/"
  weight = 2
