# Meta Data for SEO

## Homepage
title = "Wahll"
titleSeparator = "-"
titleAddition = "Open source coding website!"
description = "Wahll is an open source coding website where anyone can learn or contribute."

## Open Graph + Twitter Cards
images = []
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = ""
schemaLogo = ""
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = ""

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a><br>Contribute at <a href=\"https://github.com/simonwahll/wahllrefcontent\">GitHub site</a> and <a href=\"https://github.com/simonwahll/wahllrefcontent\">GitHub content</a><br>Page is licensed under the <a href=\"https://github.com/simonwahll/wahll/blob/master/LICENSE\">MIT license</a> and the content is licensed under the <a href=\"https://github.com/simonwahll/wahllcontent/blob/main/LICENSE\">CC0 license</a>."

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = false
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
