# Meta Data for SEO

## Homepage
title = "Wahll"
titleSeparator = "-"
titleAddition = "Programming goodies!"
description = "Programming and more!"

## Open Graph + Twitter Cards
images = []
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = ""
schemaLogo = ""
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = ""

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>.<br>Contribute at <a href=\"https://github.com/simonwahll/wahllrefcontent\">website</a> and <a href=\"https://github.com/simonwahll/wahllrefcontent\">content</a>.<br>The content on this page is licensed under the <a href=\"https://github.com/simonwahll/wahllcontent/blob/main/LICENSE\">CC0 license</a>.<br>Donate: BTC: bc1qpjslh8c076c6864vmwk0hjkg3yc04g7p2qklk2<br>XMR: 8BAVwFV6vtxC61tk5k2yYHLn6BzCw6hVdFp55GY8athEMCMtyQw9deK9aj1WGLGyQVTV64smrqk7GUE9vDVCsv8zRyXTpgR"

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = "https://github.com/simonwahll/wahllcontent/tree/main"
editPage = true

[options]
  lazySizes = true
  clipBoard = false
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
